101 rh implementing skills list
DPI-Group-Project/MentorshipPlatform pull request #132
Opened 2024-11-04 22:26 UTC by rezahusain

![skills_list](https://github.com/user-attachments/assets/7fa80099-9d18-4ba0-8aba-4144a9227a34)

Hey guys,

Sorry for the delay regarding the implementation of skills list. Originally tried to use Javascript, however it wasn't working no matter how hard I tried to debug it. Ended up using checkboxes for the user to click on with the label of each corresponding skill next to them. After sign up, each skill is added to the skills array for future usage. I didn't add any "required amount" to the amount of skills being selected since we are not using the skills for the matching algorithm. 
Also fixed some issues with the dev.rake and the registrations controller where the cohort member association wasn't being named properly.
If you guys have any requests I'm more than open to making changes to the code. Just shoot me a message!

Reza

2024-11-05 23:37 UTC, MayaS1111 approved these changes
Honestly not what I was hoping for, but I understand. Thanks

2024-11-05 23:43 UTC, MayaS1111 requested changes
Why is cohort_member association singular?

2024-11-05 23:43 UTC, MayaS1111 commented on app/controllers/users/registrations_controller.rb
> +        if resource.cohort_member.any?
why is this signal?

2024-11-05 23:43 UTC, MayaS1111 commented on lib/tasks/dev.rake
> +    cohort_member_mentee = mentee.cohort_member
why is this signal?

2024-11-06 01:10 UTC, YoungSong99 approved these changes
Thanks Reza
I think we can implement search the skills and if there is no skill user wants to put, adding the skill for next step.

2024-11-08 19:28 UTC, MayaS1111 approved these changes
All good now

2024-11-08 19:28 UTC, merged